#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

PROG="/usr/bin/mwan3_auth.sh"
PIDFILE="/var/run/mwan3_auth.pid"

# 启动服务
start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param pidfile "$PIDFILE"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

# 系统启动时等待网络就绪
boot() {
    sleep 15
    start
}